# Generated by Django 4.2.7 on 2025-12-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('skills_required', models.JSONField(default=list)),
                ('experience_required', models.CharField(max_length=100)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('platform', models.CharField(choices=[('naukri', 'Naukri'), ('internshala', 'Internshala'), ('indeed', 'Indeed'), ('linkedin', 'LinkedIn'), ('apna', 'Apna')], max_length=20)),
                ('external_url', models.URLField()),
                ('posted_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('results_count', models.IntegerField(default=0)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
