# Generated by Django 4.2.7 on 2025-12-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_applications', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('top_matching_roles', models.JSONField(default=list)),
                ('skill_gaps', models.JSONField(default=list)),
                ('improvement_suggestions', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_score', models.FloatField()),
                ('skill_match_score', models.FloatField()),
                ('experience_score', models.FloatField()),
                ('overall_score', models.FloatField()),
                ('recommendations', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpost')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.resume')),
            ],
            options={
                'unique_together': {('resume', 'job_post')},
            },
        ),
    ]
